### ISSUE TITLE
Setting Up the AWS IoT Service for the Insight on Things Application

### ISSUE THREAD

**Issue by afaideen** [MicrochipTech/aws-iot-insight-on-things-desktop-app#2]
Instruction num 5 had mistyping error.
The mistyping instruction is,
aws iam attach-group-policy --policy-arn arn:aws:iam:[AWS Account Number]:aws:policy/iotDemoPolicy --group-name iotDemo

where the instruction to be replaced is
aws iam attach-group-policy --policy-arn arn:aws:iam::[AWS Account Number]:policy/iotDemoPolicy --group-name iotDemo

That's all n all.

**Comment by bellhop** [comment]
Thank you for reporting that.  We will work to fix it and push a new release.
